### ISSUE TITLE
Anonymizer failing since no aggregations in query

### ISSUE THREAD

**Issue by christophercutajar** [elastic/anonymize-it#28]
When the query in the anonymiser doesn't have an aggregation, the anonymizer fails since it will be `null` 

```
Traceback (most recent call last):
  File "anonymize.py", line 41, in <module>
    anon.anonymize(infer=True, include_rest=config.include_rest)
  File "/Users/christophercutajar/Documents/Tools/anonymize-it/anonymize_it/anonymizers.py", line 161, in anonymize
    self.field_maps = self.reader.create_mappings(high_cardinality_fields=self.high_cardinality_fields)
  File "/Users/christophercutajar/Documents/Tools/anonymize-it/anonymize_it/readers.py", line 126, in create_mappings
    term = response['aggregations']["my_buckets"]['buckets'][-1]['key'][field]
IndexError: list index out of range
```

**Comment by christophercutajar** [comment]
Fixed in PR #30
